import { AxiosError } from 'axios'
import { format } from 'date-fns'
import {
  apiClient,
  type ApiResponse,
  type PaginatedResponse,
} from '@/lib/api-client'
import {
  type ClientFilters,
  type LocationOption,
  type SaleOption,
  normalizeSubmission,
} from './schema'

export type SubmissionListParams = ClientFilters & {
  page: number
  limit: number
}

export async function getSubmissions(
  params: SubmissionListParams,
  signal?: AbortSignal
) {
  const res = await apiClient.get<PaginatedResponse<unknown>>(
    '/admin/submissions',
    { params, signal }
  )
  return {
    data: (res.data.data ?? []).map(normalizeSubmission),
    pagination: res.data.pagination,
  }
}

export async function getSubmission(id: string, signal?: AbortSignal) {
  const res = await apiClient.get<ApiResponse<unknown>>(
    `/admin/submissions/${encodeURIComponent(id)}`,
    { signal }
  )
  return normalizeSubmission(res.data.data)
}

function filenameFromDisposition(header: unknown) {
  if (typeof header !== 'string') return null
  const encoded = /filename\*=UTF-8''([^;]+)/i.exec(header)?.[1]
  if (encoded) {
    try {
      return decodeURIComponent(encoded.trim())
    } catch {
      // fall through to the plain filename
    }
  }
  return /filename="?([^";]+)"?/i.exec(header)?.[1]?.trim() ?? null
}

/** Downloads the Excel file generated by the backend for the given filters. */
export async function exportSubmissions(filters: ClientFilters) {
  try {
    const res = await apiClient.get<Blob>('/admin/submissions/export', {
      params: filters,
      responseType: 'blob',
      // Large exports can take a while to generate
      timeout: 5 * 60 * 1000,
    })
    const filename =
      filenameFromDisposition(res.headers['content-disposition']) ??
      `client-submissions-${format(new Date(), 'yyyy-MM-dd')}.xlsx`
    return { blob: res.data, filename }
  } catch (error) {
    // Error bodies arrive as a Blob because of responseType; decode the JSON message
    if (error instanceof AxiosError && error.response?.data instanceof Blob) {
      try {
        error.response.data = JSON.parse(await error.response.data.text())
      } catch {
        error.response.data = {}
      }
    }
    throw error
  }
}

export async function getProvinces() {
  const res = await apiClient.get<ApiResponse<LocationOption[]>>(
    '/public/locations/provinces'
  )
  return res.data.data
}

export async function getDistricts(provinceId: string) {
  const res = await apiClient.get<ApiResponse<LocationOption[]>>(
    '/public/locations/districts',
    { params: { provinceId } }
  )
  return res.data.data
}

/** Communes of a district; with provinceId, they must also belong to that province */
export async function getCommunes(districtId: string, provinceId?: string) {
  const res = await apiClient.get<ApiResponse<LocationOption[]>>(
    '/public/locations/communes',
    { params: { districtId, provinceId } }
  )
  return res.data.data
}

export async function getSales() {
  const res = await apiClient.get<ApiResponse<SaleOption[]>>('/public/sales')
  return res.data.data
}
